#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PAYUCHECKOUTPROBASEKIT_SWIFT_H
#define PAYUCHECKOUTPROBASEKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import PayUParamsKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayUCheckoutProBaseKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit15BaseAPIResponse")
@interface BaseAPIResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUPaymentParam;
@class OnePayUBaseConfig;
@protocol OnePayUBaseLayerDelegate;
@protocol OnePayUBaseIndividualPaymentDelegate;
@class EMI;
@class PayUEmiCalculationDetails;
@class FetchPaymentOptionResponse;
@class PaymentOption;
enum ScreenState : NSInteger;
@class UIViewController;
@class NSString;
@class CardBinInfo;
@class PayUModelIFSCInfo;
@class ImageParam;
@class UIImage;
@class CheckEligibilityResponse;
@class PaymentMode;
@class PayUModelAllOfferDetail;
@class PayUModelOfferDetail;
@class PayULanguage;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit9BaseLayer")
@interface BaseLayer : NSObject
@property (nonatomic, strong) PayUPaymentParam * _Nonnull basePaymentParam;
@property (nonatomic, strong) OnePayUBaseConfig * _Nonnull config;
@property (nonatomic, weak) id <OnePayUBaseLayerDelegate> _Nullable delegate;
@property (nonatomic, weak) id <OnePayUBaseIndividualPaymentDelegate> _Nullable individualPaymentDelegate;
- (nonnull instancetype)initWithPaymentParam:(PayUPaymentParam * _Nonnull)paymentParam config:(OnePayUBaseConfig * _Nullable)config OBJC_DESIGNATED_INITIALIZER;
- (void)fetchEMICalculationWithEmi:(EMI * _Nonnull)emi onCompletion:(void (^ _Nonnull)(NSArray<PayUEmiCalculationDetails *> * _Nullable, NSError * _Nullable))onCompletion;
- (void)fetchPaymentOptionsOnCompletion:(void (^ _Nonnull)(FetchPaymentOptionResponse * _Nonnull))onCompletion;
- (void)makePaymentWithPaymentOption:(PaymentOption * _Nonnull)paymentOption screenState:(enum ScreenState)screenState onViewController:(UIViewController * _Nonnull)onViewController onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (BOOL)cancelCurrentPayment SWIFT_WARN_UNUSED_RESULT;
- (void)getBinInfoOfCardNumber:(NSString * _Nonnull)cardNumber onCompletion:(void (^ _Nonnull)(CardBinInfo * _Nullable, NSError * _Nullable))onCompletion;
- (void)fetchMCPLookupDataWithCardBinInfo:(CardBinInfo * _Nonnull)cardBinInfo onCompletion:(void (^ _Nonnull)(void))onCompletion;
- (void)fetchIFSCDetails:(NSString * _Nonnull)ifscCode onCompletion:(void (^ _Nonnull)(PayUModelIFSCInfo * _Nullable, NSString * _Nullable))onCompletion;
- (void)getBalanceFromSodexo:(NSString * _Nonnull)sourceId;
- (void)getBalanceFromCLWWithMobile:(NSString * _Nonnull)mobile bankCode:(NSString * _Nonnull)bankCode;
- (void)imageOf:(ImageParam * _Nonnull)imageParam onCompletion:(void (^ _Nonnull)(UIImage * _Nullable, NSInteger))onCompletion;
- (void)checkEligibilityWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (void)fetchEMIDetailsOnCompletion:(void (^ _Nonnull)(PaymentMode * _Nullable, NSError * _Nullable))onCompletion;
- (void)deleteSavedOptionWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(CheckEligibilityResponse * _Nonnull))onCompletion;
- (void)fetchOfferDetailOnCompletion:(void (^ _Nonnull)(PayUModelAllOfferDetail * _Nullable, id _Nullable, NSError * _Nullable))onCompletion;
- (void)validateOfferDetailWithPaymentOption:(PaymentOption * _Nonnull)paymentOption onCompletion:(void (^ _Nonnull)(PayUModelOfferDetail * _Nullable, NSError * _Nullable))onCompletion;
- (void)postAdsImpressionEventWithRequestId:(NSString * _Nullable)requestId;
- (void)sendMobileVerificationCodeWithMobileNumber:(NSString * _Nullable)mobileNumber onCompletion:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable))onCompletion;
- (void)verifyOtpWithMobileNumber:(NSString * _Nonnull)mobileNumber otp:(NSString * _Nonnull)otp uuid:(NSString * _Nonnull)uuid onCompletion:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable))onCompletion;
- (void)resendMobileVerificationCodeWithUuid:(NSString * _Nonnull)uuid mobileNumber:(NSString * _Nonnull)mobileNumber onCompletion:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable))onCompletion;
- (void)logout;
- (void)fetchRecommendedAndQuickPayOptionsWithToken:(NSString * _Nonnull)token mobileNumber:(NSString * _Nonnull)mobileNumber;
- (void)fetchLanguageOptionsOnCompletion:(void (^ _Nonnull)(NSArray<PayULanguage *> * _Nonnull, enum PayULanguageCode))onCompletion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit24CheckEligibilityResponse")
@interface CheckEligibilityResponse : BaseAPIResponse
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit26FetchPaymentOptionResponse")
@interface FetchPaymentOptionResponse : BaseAPIResponse <NSCopying>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit10ImageParam")
@interface ImageParam : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit8NextStep")
@interface NextStep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PayUFontFamily;
@class UIColor;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit17OnePayUBaseConfig")
@interface OnePayUBaseConfig : NSObject <NSCopying>
@property (nonatomic, copy) NSString * _Nullable merchantName;
@property (nonatomic, strong) UIImage * _Nullable merchantLogo;
@property (nonatomic, copy) NSString * _Nullable merchantLogoURL;
@property (nonatomic) BOOL showMerchantLogo;
@property (nonatomic, copy) NSArray<PaymentMode *> * _Nullable paymentModesOrder;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, NSString *> *> * _Nullable cartDetails;
@property (nonatomic) BOOL showExitConfirmationOnCheckoutScreen;
@property (nonatomic) BOOL showExitConfirmationOnPaymentScreen;
@property (nonatomic) enum PayULanguageCode merchantLanguage;
@property (nonatomic, readonly) BOOL showUserCancellationDialogue;
@property (nonatomic, strong) PayUFontFamily * _Nullable fontfamily;
@property (nonatomic) BOOL enableSavedCard;
@property (nonatomic) BOOL isProtectedScreen;
@property (nonatomic, copy) NSString * _Nullable upiAppsOrder;
@property (nonatomic, readonly, strong) UIColor * _Nullable primaryColor;
@property (nonatomic, readonly, strong) UIColor * _Nullable secondaryColor;
- (void)customiseUIWithPrimaryColor:(UIColor * _Nonnull)primaryColor secondaryColor:(UIColor * _Nonnull)secondaryColor;
- (void)setPrimaryColor:(UIColor * _Nullable)color;
- (void)setSecondaryColor:(UIColor * _Nullable)color;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit36OnePayUBaseIndividualPaymentDelegate_")
@protocol OnePayUBaseIndividualPaymentDelegate
- (void)upiCollectTransactionRemainingTime:(NSInteger)remainingTime;
@end


SWIFT_PROTOCOL("_TtP22PayUCheckoutProBaseKit24OnePayUBaseLayerDelegate_")
@protocol OnePayUBaseLayerDelegate
- (void)paymentSuccessWithResponse:(id _Nullable)response;
- (void)paymentFailureWithResponse:(id _Nullable)response;
- (void)paymentCancelledWithResponse:(id _Nullable)response fromPaymentScreen:(BOOL)fromPaymentScreen;
- (void)error:(NSError * _Nullable)error;
- (void)getHashFor:(NSDictionary<NSString *, NSString *> * _Nonnull)param onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, NSString *> * _Nonnull))onCompletion;
- (void)nextStep:(NextStep * _Nullable)nextStep;
- (void)loadRetryPaymentOption;
@end

@class PayUCustomNote;

SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit21PayUCheckoutProConfig")
@interface PayUCheckoutProConfig : OnePayUBaseConfig
@property (nonatomic) NSUInteger surePayCount SWIFT_DEPRECATED_MSG("This feature is no longer supported by the SDK");
@property (nonatomic) BOOL autoSelectOtp;
@property (nonatomic) BOOL autoSubmitOtp;
@property (nonatomic) NSTimeInterval merchantResponseTimeout;
@property (nonatomic) NSTimeInterval sodexoCardBalanceAPITimeout;
@property (nonatomic, copy) NSArray<PayUCustomNote *> * _Nullable customNotes;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable enforcePaymentList;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC22PayUCheckoutProBaseKit14PayUCustomNote")
@interface PayUCustomNote : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ScreenState, open) {
  ScreenStateNone = 0,
  ScreenStatePhoneNumberScreen = 1,
  ScreenStateVpaEntry = 2,
  ScreenStateUpiIntentProcessing = 3,
  ScreenStateUpiCollectProcessing = 4,
  ScreenStateCurrencySelection = 5,
  ScreenStateAddCard = 6,
  ScreenStateBankDetails = 7,
  ScreenStateLoadAmount = 8,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
